let TranslationLanguage = [];

TranslationLanguage['English'] = {
    To_Do_List:'To-Do List',
    organize_task:'Organize your tasks, stay on track, and conquer your day, one checkmark at a time!',
    AdNotes:'Ad Notes',
    quickly_jot_down:'Quickly jot down your ideas, tasks, and reminders all in one place!',
    Calender:'Calendar',
    stay_organized:'Stay organized by scheduling and tracking all your events, tasks',
    conitnue:'Continue',
    TaskNexus:'TaskNexus',
    no_notes:'No Notes',
    you_havent_create_any_note_yet:`You haven't created any note yet!`,
    create_note:'Create Note',
    search:'Search',
    Notes:'Notes',
    Todo:'Todo',
    Calender:'Calender',
    Setting:'Setting',
    Todo:'Todo',
    no_todo_found:'No Todo founds',
    privacy_policy:'Privacy Policy',
    RateUs:'Rate Us',
    Share_App:'Share App'
},
TranslationLanguage['Portuguese'] = {
    To_Do_List:'Lista de tarefas',
    organize_task:'Organize suas tarefas, mantenha o controle e conquiste seu dia, uma marca de cada vez!',
    AdNotes:'Notas de anúncio',
    quickly_jot_down:'Anote rapidamente suas ideias, tarefas e lembretes em um só lugar!',
    Calender:'Calendário',
    stay_organized:'Mantenha-se organizado agendando e acompanhando todos os seus eventos e tarefas',
    conitnue:'Continuar',
    TaskNexus:'TaskNexus',
    no_notes:'Sem notas',
    you_havent_create_any_note_yet:`Você ainda não criou nenhuma nota!`,
    create_note:'Criar nota',
    search:'Procurar',
    Notes:'Notas',
    Todo:'Pendência',
    Calender:'Calendário',
    Setting:'Contexto',
    Todo:'Pendência',
    no_todo_found:'Nenhum Todo fundado',
    privacy_policy:'política de Privacidade',
    RateUs:'Avalie-nos',
    Share_App:'Compartilhar aplicativo'
},
TranslationLanguage['Spanish'] = {
    To_Do_List:'Lista de tareas pendientes',
    organize_task:'Organiza tus tareas, mantén el rumbo y conquista tu día, ¡una marca de verificación a la vez!',
    AdNotes:'Notas publicitarias',
    quickly_jot_down:'Anota rápidamente tus ideas, tareas y recordatorios, todo en un solo lugar!',
    Calender:'Calendario',
    stay_organized:'Manténgase organizado programando y rastreando todos sus eventos y tareas',
    conitnue:'Continuar',
    TaskNexus:'TareaNexus',
    no_notes:'Sin notas',
    you_havent_create_any_note_yet:`Aún no has creado ninguna nota!`,
    create_note:'Crear nota',
    search:'Buscar',
    Notes:'Notas',
    Todo:'Hacer',
    Calender:'Calendario',
    Setting:'Configuración',
    Todo:'Hacer',
    no_todo_found:'No todo funda',
    privacy_policy:'política de privacidad',
    RateUs:'Califícanos',
    Share_App:'Compartir aplicación'
},
TranslationLanguage['Hindi'] = {
    To_Do_List:'करने के लिए सूची',
    organize_task:'अपने कार्यों को व्यवस्थित करें, ट्रैक पर बने रहें और एक समय में एक चेकमार्क से अपना दिन जीतें!',
    AdNotes:'विज्ञापन नोट्स',
    quickly_jot_down:'अपने विचारों, कार्यों और अनुस्मारकों को एक ही स्थान पर तुरंत लिखें!',
    Calender:'Calendar',
    stay_organized:'अपने सभी आयोजनों, कार्यों को शेड्यूल और ट्रैक करके व्यवस्थित रहें',
    conitnue:'जारी रखना',
    TaskNexus:'टास्कनेक्सस',
    no_notes:'कोई नोट्स नहीं',
    you_havent_create_any_note_yet:`आपने अभी तक कोई नोट नहीं बनाया है!`,
    create_note:'नोट बनाएँ',
    search:'खोज',
    Notes:'टिप्पणियाँ',
    Todo:'करने के लिए',
    Calender:'कैलेंडर',
    Setting:'सेटिंग',
    Todo:'करने के लिए',
    no_todo_found:'कोई टोडो नहीं मिला',
    privacy_policy:'गोपनीयता नीति',
    RateUs:'हमें रेटिंग दें',
    Share_App:'ऐप साझा करें'
},
TranslationLanguage['Korean'] = {
    To_Do_List:'할 일 목록',
    organize_task:'한 번에 하나씩 체크 표시를 하여 작업을 정리하고 순조롭게 하루를 마무리하세요!',
    AdNotes:'광고 메모',
    quickly_jot_down:'아이디어, 할 일, 알림 등을 모두 한 곳에 빠르게 적어보세요!',
    Calender:'달력',
    stay_organized:'모든 이벤트, 작업을 예약하고 추적하여 체계적으로 정리하세요.',
    conitnue:'계속하다',
    TaskNexus:'태스크넥서스',
    no_notes:'메모 없음',
    you_havent_create_any_note_yet:`아직 메모를 작성하지 않았습니다.`,
    create_note:'메모 작성',
    search:'찾다',
    Notes:'메모',
    Todo:'토도',
    Calender:'달력',
    Setting:'환경',
    Todo:'토도',
    no_todo_found:'Todo를 찾을 수 없습니다.',
    privacy_policy:'개인 정보 보호 정책',
    RateUs:'우리를 평가해 주세요',
    Share_App:'앱 공유'
},
TranslationLanguage['French'] = {
    To_Do_List:'Liste de tâches',
    organize_task:'Organisez vos tâches, restez sur la bonne voie et conquérez votre journée, une coche à la fois !',
    AdNotes:'Notes publicitaires',
    quickly_jot_down:'Notez rapidement vos idées, tâches et rappels au même endroit !',
    Calender:'Calendrier',
    stay_organized:'Restez organisé en planifiant et en suivant tous vos événements et tâches',
    conitnue:'Continuer',
    TaskNexus:'TâcheNexus',
    no_notes:'Aucune remarque',
    you_havent_create_any_note_yet:`Vous n'avez encore créé aucune note !`,
    create_note:'Créer une note',
    search:'Recherche',
    Notes:'Remarques',
    Todo:'Faire',
    Calender:'Calendrier',
    Setting:'Paramètre',
    Todo:'Faire',
    no_todo_found:'Aucun Todo trouvé',
    privacy_policy:'politique de confidentialité',
    RateUs:'Évaluez-nous',
    Share_App:`Partager l'application`
},
TranslationLanguage['Urdu'] = {
    To_Do_List:'کرنے کی فہرست',
    organize_task:'اپنے کاموں کو منظم کریں، ٹریک پر رہیں، اور اپنے دن کو فتح کریں، ایک وقت میں ایک چیک مارک!',
    AdNotes:'اشتھاراتی نوٹس',
    quickly_jot_down:'اپنے خیالات، کاموں، اور یاد دہانیوں کو ایک جگہ پر جلدی سے لکھیں',
    Calender:'کیلنڈر',
    stay_organized:'اپنے تمام واقعات، کاموں کو شیڈول اور ٹریک کرکے منظم رہیں',
    conitnue:'جاری رکھیں',
    TaskNexus:'TaskNexus',
    no_notes:'کوئی نوٹس نہیں۔',
    you_havent_create_any_note_yet:`پ نے ابھی تک کوئی نوٹ نہیں بنایا ہے!`,
    create_note:'نوٹ بنائیں',
    search:'تلاش کریں۔',
    Notes:'نوٹس',
    Todo:'ٹوڈو',
    Calender:'کیلنڈر',
    Setting:'ترتیب',
    Todo:'ٹوڈو',
    no_todo_found:'کوئی ٹوڈو نہیں ملا',
    privacy_policy:'رازداری کی پالیسی',
    RateUs:'ہمیں درجہ دیں۔',
    Share_App:'ایپ شیئر کریں۔'
},
TranslationLanguage['Japanese'] = {
    To_Do_List:'やることリスト',
    organize_task:'タスクを整理し、順調に進み、チェックマークを 1 つずつこなしながら 1 日を制覇しましょう。',
    AdNotes:'広告メモ',
    quickly_jot_down:'アイデア、タスク、リマインダーをすべて 1 か所にすばやく書き留めましょう。',
    Calender:'カレンダー',
    stay_organized:'すべてのイベントやタスクをスケジュールして追跡することで、整理整頓を維持します',
    conitnue:'続く',
    TaskNexus:'タスクネクサス',
    no_notes:'メモなし',
    you_havent_create_any_note_yet:`まだメモを作成していません。`,
    create_note:'メモの作成',
    search:'検索',
    Notes:'注意事項',
    Todo:'藤堂',
    Calender:'カレンダー',
    Setting:'設定',
    Todo:'藤堂',
    no_todo_found:'Todo が見つかりません',
    privacy_policy:'プライバシーポリシ',
    RateUs:'評価してください',
    Share_App:'アプリを共有する'
}
export default TranslationLanguage