const SET_HOME_SCREEN = 'SET_HOME_SCREEN';
const ADD_NOTE = 'ADD_NOTE';
const UPDATE_NOTE = 'UPDATE_NOTE';
const DELETE_NOTE = 'DELETE_NOTE';
const ADD_TODO = 'ADD_TODO';
const TOGGLE_TODO_COMPLETION = 'TOGGLE_TODO_COMPLETION'
const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
const ADD_TASK = 'ADD_TASK'
export {SET_HOME_SCREEN, ADD_NOTE, UPDATE_NOTE, DELETE_NOTE,ADD_TODO,TOGGLE_TODO_COMPLETION,CHANGE_LANGUAGE,ADD_TASK};
